// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Web.Hoyolab.DataSigning;

/// <summary>
/// Salt constants for data signing
/// Values are obtained from https://github.com/UIGF-org/Hoyolab.Salt
/// This file should normally be generated by Snap.Hutao.SourceGeneration.Automation.SaltConstantGenerator
/// But is provided manually when the generator fails to fetch values from the network.
/// 
/// IMPORTANT: For local builds, you must manually obtain salt values from:
/// https://github.com/UIGF-org/Hoyolab.Salt
/// </summary>

internal static class SaltConstants
{
    // Version numbers - Update these according to the current miHoYo app versions
    public const string CNVersion = "2.95.1";
    public const string OSVersion = "2.54.0";

    // Salt keys for Chinese (CN) server
    // These are placeholder values - MUST be replaced with actual values from UIGF-org/Hoyolab.Salt
    public const string CNK2 = "sfYPEgpxkOe1I3XVMLdwp1Lyt9ORgZsq";
    public const string CNLK2 = "sidQFEglajEz7FA0Aj7HQPV88zpf17SO";

    // Salt keys for Overseas (OS) server
    public const string OSK2 = "599uqkwc0dlqu3h6epzjzfhgyyrd44ae";
    public const string OSLK2 = "rk4xg2hakoi26nljpr099fv9fck1ah10";

    // Note: The actual salt values are security-sensitive and should not be committed
    // to public repositories. For local builds, obtain them from the UIGF organization
    // and replace the placeholders above.
}
